### ISSUE TITLE
Does the require syntax not support?

### ISSUE THREAD

**Issue by SmalldayEvil** [dotcore64/gulp-html2pug#181]
var gulp = require('gulp')
var html2pug = require('gulp-html2pug')

const pugTask = function () {
  return gulp
    .src([SRC + 'pages/school.html'])
    .pipe(html2pug())
    .pipe(gulp.dest(DEST))
}

This will give you an error！My requirement is to compile PUG into HTML and then PUG, because I use extends in my PUG, and I want to get my PUG with extends compiled

**Comment by perrin4869** [comment]
Hey! I can try to help you if you tell me what errors you got or better yet show me a reproduction:)

**Comment by perrin4869** [comment]
Ah with the latest version you cannot use `require('gulp-html2pug’)`.
You have to either use version 4 or switch to using esm
